<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AssemblyInfo.json" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\App.ico" />
    <Resource Include="Resources\App.png" />
    <Resource Include="Resources\MainMenuControl.png" />
    <Resource Include="Resources\Settings.png" />
    <Resource Include="Resources\StatusInformation.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Config\appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\appsettings.Development.json">
      <DependentUpon>Config\appsettings.json</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="Config\NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\NLog.Development.config">
      <DependentUpon>Config\NLog.config</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="5.3.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Loginator.Application\Loginator.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).UnitTests" />
  </ItemGroup>
</Project>
