<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).UnitTests" />
    <InternalsVisibleTo Include="Loginator.Infrastructure" />
    <InternalsVisibleTo Include="Loginator.Infrastructure.UnitTests" />
    <InternalsVisibleTo Include="Loginator.Application.UnitTests" />
  </ItemGroup>
</Project>
